/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppModerationRouteImport } from './routes/_app/moderation'
import { Route as AppBookmarksRouteImport } from './routes/_app/bookmarks'
import { Route as AppCommunitiesIndexRouteImport } from './routes/_app/communities.index'
import { Route as AppUsersIdRouteImport } from './routes/_app/users.$id'
import { Route as AppPublicationsIdRouteImport } from './routes/_app/publications.$id'
import { Route as AppFeedAnnouncementsRouteImport } from './routes/_app/feed.announcements'
import { Route as AppCommunitiesCreateRouteImport } from './routes/_app/communities.create'
import { Route as AppCommunitiesIdRouteImport } from './routes/_app/communities.$id'
import { Route as AppUsersIdIndexRouteImport } from './routes/_app/users.$id.index'
import { Route as AppPublicationsIdIndexRouteImport } from './routes/_app/publications.$id.index'
import { Route as AppCommunitiesIdIndexRouteImport } from './routes/_app/communities.$id.index'
import { Route as AppUsersIdSettingsRouteImport } from './routes/_app/users.$id.settings'
import { Route as AppPublicationsIdEditRouteImport } from './routes/_app/publications.$id.edit'
import { Route as AppFeedLabelLabelRouteImport } from './routes/_app/feed.label.$label'
import { Route as AppFeedCareerCareerCodeRouteImport } from './routes/_app/feed.career.$careerCode'
import { Route as AppCommunitiesIdMembersRouteImport } from './routes/_app/communities.$id.members'
import { Route as AppCommunitiesIdEditRouteImport } from './routes/_app/communities.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicationsIdRoute = AppPublicationsIdRouteImport.update({
  id: '/publications/$id',
  path: '/publications/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedAnnouncementsRoute = AppFeedAnnouncementsRouteImport.update({
  id: '/feed/announcements',
  path: '/feed/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesCreateRoute = AppCommunitiesCreateRouteImport.update({
  id: '/communities/create',
  path: '/communities/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIdRoute = AppCommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdIndexRoute = AppUsersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersIdRoute,
} as any)
const AppPublicationsIdIndexRoute = AppPublicationsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPublicationsIdRoute,
} as any)
const AppCommunitiesIdIndexRoute = AppCommunitiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCommunitiesIdRoute,
} as any)
const AppUsersIdSettingsRoute = AppUsersIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppUsersIdRoute,
} as any)
const AppPublicationsIdEditRoute = AppPublicationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppPublicationsIdRoute,
} as any)
const AppFeedLabelLabelRoute = AppFeedLabelLabelRouteImport.update({
  id: '/feed/label/$label',
  path: '/feed/label/$label',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedCareerCareerCodeRoute = AppFeedCareerCareerCodeRouteImport.update({
  id: '/feed/career/$careerCode',
  path: '/feed/career/$careerCode',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIdMembersRoute = AppCommunitiesIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppCommunitiesIdRoute,
} as any)
const AppCommunitiesIdEditRoute = AppCommunitiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppCommunitiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/moderation': typeof AppModerationRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/communities/$id': typeof AppCommunitiesIdRouteWithChildren
  '/communities/create': typeof AppCommunitiesCreateRoute
  '/feed/announcements': typeof AppFeedAnnouncementsRoute
  '/publications/$id': typeof AppPublicationsIdRouteWithChildren
  '/users/$id': typeof AppUsersIdRouteWithChildren
  '/communities/': typeof AppCommunitiesIndexRoute
  '/communities/$id/edit': typeof AppCommunitiesIdEditRoute
  '/communities/$id/members': typeof AppCommunitiesIdMembersRoute
  '/feed/career/$careerCode': typeof AppFeedCareerCareerCodeRoute
  '/feed/label/$label': typeof AppFeedLabelLabelRoute
  '/publications/$id/edit': typeof AppPublicationsIdEditRoute
  '/users/$id/settings': typeof AppUsersIdSettingsRoute
  '/communities/$id/': typeof AppCommunitiesIdIndexRoute
  '/publications/$id/': typeof AppPublicationsIdIndexRoute
  '/users/$id/': typeof AppUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/moderation': typeof AppModerationRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AppIndexRoute
  '/communities/create': typeof AppCommunitiesCreateRoute
  '/feed/announcements': typeof AppFeedAnnouncementsRoute
  '/communities': typeof AppCommunitiesIndexRoute
  '/communities/$id/edit': typeof AppCommunitiesIdEditRoute
  '/communities/$id/members': typeof AppCommunitiesIdMembersRoute
  '/feed/career/$careerCode': typeof AppFeedCareerCareerCodeRoute
  '/feed/label/$label': typeof AppFeedLabelLabelRoute
  '/publications/$id/edit': typeof AppPublicationsIdEditRoute
  '/users/$id/settings': typeof AppUsersIdSettingsRoute
  '/communities/$id': typeof AppCommunitiesIdIndexRoute
  '/publications/$id': typeof AppPublicationsIdIndexRoute
  '/users/$id': typeof AppUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/moderation': typeof AppModerationRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/search': typeof AppSearchRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/communities/$id': typeof AppCommunitiesIdRouteWithChildren
  '/_app/communities/create': typeof AppCommunitiesCreateRoute
  '/_app/feed/announcements': typeof AppFeedAnnouncementsRoute
  '/_app/publications/$id': typeof AppPublicationsIdRouteWithChildren
  '/_app/users/$id': typeof AppUsersIdRouteWithChildren
  '/_app/communities/': typeof AppCommunitiesIndexRoute
  '/_app/communities/$id/edit': typeof AppCommunitiesIdEditRoute
  '/_app/communities/$id/members': typeof AppCommunitiesIdMembersRoute
  '/_app/feed/career/$careerCode': typeof AppFeedCareerCareerCodeRoute
  '/_app/feed/label/$label': typeof AppFeedLabelLabelRoute
  '/_app/publications/$id/edit': typeof AppPublicationsIdEditRoute
  '/_app/users/$id/settings': typeof AppUsersIdSettingsRoute
  '/_app/communities/$id/': typeof AppCommunitiesIdIndexRoute
  '/_app/publications/$id/': typeof AppPublicationsIdIndexRoute
  '/_app/users/$id/': typeof AppUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/bookmarks'
    | '/moderation'
    | '/notifications'
    | '/onboarding'
    | '/rules'
    | '/search'
    | '/oauth/callback'
    | '/communities/$id'
    | '/communities/create'
    | '/feed/announcements'
    | '/publications/$id'
    | '/users/$id'
    | '/communities/'
    | '/communities/$id/edit'
    | '/communities/$id/members'
    | '/feed/career/$careerCode'
    | '/feed/label/$label'
    | '/publications/$id/edit'
    | '/users/$id/settings'
    | '/communities/$id/'
    | '/publications/$id/'
    | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/bookmarks'
    | '/moderation'
    | '/notifications'
    | '/onboarding'
    | '/rules'
    | '/search'
    | '/oauth/callback'
    | '/'
    | '/communities/create'
    | '/feed/announcements'
    | '/communities'
    | '/communities/$id/edit'
    | '/communities/$id/members'
    | '/feed/career/$careerCode'
    | '/feed/label/$label'
    | '/publications/$id/edit'
    | '/users/$id/settings'
    | '/communities/$id'
    | '/publications/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/bookmarks'
    | '/_app/moderation'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/rules'
    | '/_app/search'
    | '/oauth/callback'
    | '/_app/'
    | '/_app/communities/$id'
    | '/_app/communities/create'
    | '/_app/feed/announcements'
    | '/_app/publications/$id'
    | '/_app/users/$id'
    | '/_app/communities/'
    | '/_app/communities/$id/edit'
    | '/_app/communities/$id/members'
    | '/_app/feed/career/$careerCode'
    | '/_app/feed/label/$label'
    | '/_app/publications/$id/edit'
    | '/_app/users/$id/settings'
    | '/_app/communities/$id/'
    | '/_app/publications/$id/'
    | '/_app/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/': {
      id: '/_app/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id': {
      id: '/_app/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publications/$id': {
      id: '/_app/publications/$id'
      path: '/publications/$id'
      fullPath: '/publications/$id'
      preLoaderRoute: typeof AppPublicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/announcements': {
      id: '/_app/feed/announcements'
      path: '/feed/announcements'
      fullPath: '/feed/announcements'
      preLoaderRoute: typeof AppFeedAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/create': {
      id: '/_app/communities/create'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof AppCommunitiesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/$id': {
      id: '/_app/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof AppCommunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id/': {
      id: '/_app/users/$id/'
      path: '/'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof AppUsersIdIndexRouteImport
      parentRoute: typeof AppUsersIdRoute
    }
    '/_app/publications/$id/': {
      id: '/_app/publications/$id/'
      path: '/'
      fullPath: '/publications/$id/'
      preLoaderRoute: typeof AppPublicationsIdIndexRouteImport
      parentRoute: typeof AppPublicationsIdRoute
    }
    '/_app/communities/$id/': {
      id: '/_app/communities/$id/'
      path: '/'
      fullPath: '/communities/$id/'
      preLoaderRoute: typeof AppCommunitiesIdIndexRouteImport
      parentRoute: typeof AppCommunitiesIdRoute
    }
    '/_app/users/$id/settings': {
      id: '/_app/users/$id/settings'
      path: '/settings'
      fullPath: '/users/$id/settings'
      preLoaderRoute: typeof AppUsersIdSettingsRouteImport
      parentRoute: typeof AppUsersIdRoute
    }
    '/_app/publications/$id/edit': {
      id: '/_app/publications/$id/edit'
      path: '/edit'
      fullPath: '/publications/$id/edit'
      preLoaderRoute: typeof AppPublicationsIdEditRouteImport
      parentRoute: typeof AppPublicationsIdRoute
    }
    '/_app/feed/label/$label': {
      id: '/_app/feed/label/$label'
      path: '/feed/label/$label'
      fullPath: '/feed/label/$label'
      preLoaderRoute: typeof AppFeedLabelLabelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/career/$careerCode': {
      id: '/_app/feed/career/$careerCode'
      path: '/feed/career/$careerCode'
      fullPath: '/feed/career/$careerCode'
      preLoaderRoute: typeof AppFeedCareerCareerCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/$id/members': {
      id: '/_app/communities/$id/members'
      path: '/members'
      fullPath: '/communities/$id/members'
      preLoaderRoute: typeof AppCommunitiesIdMembersRouteImport
      parentRoute: typeof AppCommunitiesIdRoute
    }
    '/_app/communities/$id/edit': {
      id: '/_app/communities/$id/edit'
      path: '/edit'
      fullPath: '/communities/$id/edit'
      preLoaderRoute: typeof AppCommunitiesIdEditRouteImport
      parentRoute: typeof AppCommunitiesIdRoute
    }
  }
}

interface AppCommunitiesIdRouteChildren {
  AppCommunitiesIdEditRoute: typeof AppCommunitiesIdEditRoute
  AppCommunitiesIdMembersRoute: typeof AppCommunitiesIdMembersRoute
  AppCommunitiesIdIndexRoute: typeof AppCommunitiesIdIndexRoute
}

const AppCommunitiesIdRouteChildren: AppCommunitiesIdRouteChildren = {
  AppCommunitiesIdEditRoute: AppCommunitiesIdEditRoute,
  AppCommunitiesIdMembersRoute: AppCommunitiesIdMembersRoute,
  AppCommunitiesIdIndexRoute: AppCommunitiesIdIndexRoute,
}

const AppCommunitiesIdRouteWithChildren =
  AppCommunitiesIdRoute._addFileChildren(AppCommunitiesIdRouteChildren)

interface AppPublicationsIdRouteChildren {
  AppPublicationsIdEditRoute: typeof AppPublicationsIdEditRoute
  AppPublicationsIdIndexRoute: typeof AppPublicationsIdIndexRoute
}

const AppPublicationsIdRouteChildren: AppPublicationsIdRouteChildren = {
  AppPublicationsIdEditRoute: AppPublicationsIdEditRoute,
  AppPublicationsIdIndexRoute: AppPublicationsIdIndexRoute,
}

const AppPublicationsIdRouteWithChildren =
  AppPublicationsIdRoute._addFileChildren(AppPublicationsIdRouteChildren)

interface AppUsersIdRouteChildren {
  AppUsersIdSettingsRoute: typeof AppUsersIdSettingsRoute
  AppUsersIdIndexRoute: typeof AppUsersIdIndexRoute
}

const AppUsersIdRouteChildren: AppUsersIdRouteChildren = {
  AppUsersIdSettingsRoute: AppUsersIdSettingsRoute,
  AppUsersIdIndexRoute: AppUsersIdIndexRoute,
}

const AppUsersIdRouteWithChildren = AppUsersIdRoute._addFileChildren(
  AppUsersIdRouteChildren,
)

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppModerationRoute: typeof AppModerationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunitiesIdRoute: typeof AppCommunitiesIdRouteWithChildren
  AppCommunitiesCreateRoute: typeof AppCommunitiesCreateRoute
  AppFeedAnnouncementsRoute: typeof AppFeedAnnouncementsRoute
  AppPublicationsIdRoute: typeof AppPublicationsIdRouteWithChildren
  AppUsersIdRoute: typeof AppUsersIdRouteWithChildren
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
  AppFeedCareerCareerCodeRoute: typeof AppFeedCareerCareerCodeRoute
  AppFeedLabelLabelRoute: typeof AppFeedLabelLabelRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppModerationRoute: AppModerationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRulesRoute: AppRulesRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunitiesIdRoute: AppCommunitiesIdRouteWithChildren,
  AppCommunitiesCreateRoute: AppCommunitiesCreateRoute,
  AppFeedAnnouncementsRoute: AppFeedAnnouncementsRoute,
  AppPublicationsIdRoute: AppPublicationsIdRouteWithChildren,
  AppUsersIdRoute: AppUsersIdRouteWithChildren,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
  AppFeedCareerCareerCodeRoute: AppFeedCareerCareerCodeRoute,
  AppFeedLabelLabelRoute: AppFeedLabelLabelRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
