/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppCommunitiesIndexRouteImport } from './routes/_app/communities.index'
import { Route as AppUsersIdRouteImport } from './routes/_app/users.$id'
import { Route as AppPublicationsIdRouteImport } from './routes/_app/publications.$id'
import { Route as AppFeedAnnouncementsRouteImport } from './routes/_app/feed.announcements'
import { Route as AppCommunitiesCreateRouteImport } from './routes/_app/communities.create'
import { Route as AppCommunitiesIdRouteImport } from './routes/_app/communities.$id'
import { Route as AppUsersIdSettingsRouteImport } from './routes/_app/users.$id.settings'
import { Route as AppFeedCareerCareerCodeRouteImport } from './routes/_app/feed.career.$careerCode'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicationsIdRoute = AppPublicationsIdRouteImport.update({
  id: '/publications/$id',
  path: '/publications/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedAnnouncementsRoute = AppFeedAnnouncementsRouteImport.update({
  id: '/feed/announcements',
  path: '/feed/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesCreateRoute = AppCommunitiesCreateRouteImport.update({
  id: '/communities/create',
  path: '/communities/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIdRoute = AppCommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdSettingsRoute = AppUsersIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppUsersIdRoute,
} as any)
const AppFeedCareerCareerCodeRoute = AppFeedCareerCareerCodeRouteImport.update({
  id: '/feed/career/$careerCode',
  path: '/feed/career/$careerCode',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/notifications': typeof AppNotificationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/communities/$id': typeof AppCommunitiesIdRoute
  '/communities/create': typeof AppCommunitiesCreateRoute
  '/feed/announcements': typeof AppFeedAnnouncementsRoute
  '/publications/$id': typeof AppPublicationsIdRoute
  '/users/$id': typeof AppUsersIdRouteWithChildren
  '/communities/': typeof AppCommunitiesIndexRoute
  '/feed/career/$careerCode': typeof AppFeedCareerCareerCodeRoute
  '/users/$id/settings': typeof AppUsersIdSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/notifications': typeof AppNotificationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/communities/$id': typeof AppCommunitiesIdRoute
  '/communities/create': typeof AppCommunitiesCreateRoute
  '/feed/announcements': typeof AppFeedAnnouncementsRoute
  '/publications/$id': typeof AppPublicationsIdRoute
  '/users/$id': typeof AppUsersIdRouteWithChildren
  '/communities': typeof AppCommunitiesIndexRoute
  '/feed/career/$careerCode': typeof AppFeedCareerCareerCodeRoute
  '/users/$id/settings': typeof AppUsersIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/communities/$id': typeof AppCommunitiesIdRoute
  '/_app/communities/create': typeof AppCommunitiesCreateRoute
  '/_app/feed/announcements': typeof AppFeedAnnouncementsRoute
  '/_app/publications/$id': typeof AppPublicationsIdRoute
  '/_app/users/$id': typeof AppUsersIdRouteWithChildren
  '/_app/communities/': typeof AppCommunitiesIndexRoute
  '/_app/feed/career/$careerCode': typeof AppFeedCareerCareerCodeRoute
  '/_app/users/$id/settings': typeof AppUsersIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/notifications'
    | '/rules'
    | '/search'
    | '/communities/$id'
    | '/communities/create'
    | '/feed/announcements'
    | '/publications/$id'
    | '/users/$id'
    | '/communities/'
    | '/feed/career/$careerCode'
    | '/users/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/notifications'
    | '/rules'
    | '/search'
    | '/'
    | '/communities/$id'
    | '/communities/create'
    | '/feed/announcements'
    | '/publications/$id'
    | '/users/$id'
    | '/communities'
    | '/feed/career/$careerCode'
    | '/users/$id/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/notifications'
    | '/_app/rules'
    | '/_app/search'
    | '/_app/'
    | '/_app/communities/$id'
    | '/_app/communities/create'
    | '/_app/feed/announcements'
    | '/_app/publications/$id'
    | '/_app/users/$id'
    | '/_app/communities/'
    | '/_app/feed/career/$careerCode'
    | '/_app/users/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/': {
      id: '/_app/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id': {
      id: '/_app/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publications/$id': {
      id: '/_app/publications/$id'
      path: '/publications/$id'
      fullPath: '/publications/$id'
      preLoaderRoute: typeof AppPublicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/announcements': {
      id: '/_app/feed/announcements'
      path: '/feed/announcements'
      fullPath: '/feed/announcements'
      preLoaderRoute: typeof AppFeedAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/create': {
      id: '/_app/communities/create'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof AppCommunitiesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/$id': {
      id: '/_app/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof AppCommunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id/settings': {
      id: '/_app/users/$id/settings'
      path: '/settings'
      fullPath: '/users/$id/settings'
      preLoaderRoute: typeof AppUsersIdSettingsRouteImport
      parentRoute: typeof AppUsersIdRoute
    }
    '/_app/feed/career/$careerCode': {
      id: '/_app/feed/career/$careerCode'
      path: '/feed/career/$careerCode'
      fullPath: '/feed/career/$careerCode'
      preLoaderRoute: typeof AppFeedCareerCareerCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppUsersIdRouteChildren {
  AppUsersIdSettingsRoute: typeof AppUsersIdSettingsRoute
}

const AppUsersIdRouteChildren: AppUsersIdRouteChildren = {
  AppUsersIdSettingsRoute: AppUsersIdSettingsRoute,
}

const AppUsersIdRouteWithChildren = AppUsersIdRoute._addFileChildren(
  AppUsersIdRouteChildren,
)

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunitiesIdRoute: typeof AppCommunitiesIdRoute
  AppCommunitiesCreateRoute: typeof AppCommunitiesCreateRoute
  AppFeedAnnouncementsRoute: typeof AppFeedAnnouncementsRoute
  AppPublicationsIdRoute: typeof AppPublicationsIdRoute
  AppUsersIdRoute: typeof AppUsersIdRouteWithChildren
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
  AppFeedCareerCareerCodeRoute: typeof AppFeedCareerCareerCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppRulesRoute: AppRulesRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunitiesIdRoute: AppCommunitiesIdRoute,
  AppCommunitiesCreateRoute: AppCommunitiesCreateRoute,
  AppFeedAnnouncementsRoute: AppFeedAnnouncementsRoute,
  AppPublicationsIdRoute: AppPublicationsIdRoute,
  AppUsersIdRoute: AppUsersIdRouteWithChildren,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
  AppFeedCareerCareerCodeRoute: AppFeedCareerCareerCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
